Nanook/Nanook/Controllers/FeedbackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Nanook.Models;

namespace Nanook.Controllers
{
    [Authorize]
    public class FeedbackController : NanookController
    {
        [HttpGet]
        public ActionResult Create(Guid questionId)
        {
            var memberId = Member.Data.ID;
            FeedbackCreateViewModel model;
            using (var poda = Poda.Factory.Create())
            {
                model = poda.Execute()
                    .ForPlainSQL("SELECT * FROM MemberQuestions WHERE ID = @ID")
                    .With("ID", questionId)
                    .FederationOn("MemberQuestions", "MemberID", memberId)
                    .AsEntities<FeedbackCreateViewModel>((reader) => new FeedbackCreateViewModel()
                    {
                        QuestionID = questionId,
                        MemberID = (Guid)reader["MemberID"],
                        QuestionTitle = (string)reader["Title"],
                        QuestionContent = (string)reader["Question"]
                    })
                    .FirstOrDefault();
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(FeedbackCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var feedbackId=Guid.NewGuid();
                var feedbackMemberId=Member.Data.ID;
                using (var poda = Poda.Factory.Create())
                {
                    poda.Execute()
                        .ForPlainSQL("INSERT INTO MemberQuestionAnswers " +
                                     "(ID, MemberID, QuestionID, Answer, PostedByID) VALUES " +
                                     "(@ID, @MemberID, @QuestionID, @Answer, @PostedByID)")
                        .With("ID", feedbackId)
                        .With("MemberID", model.MemberID)
                        .With("QuestionID", model.QuestionID)
                        .With("Answer", model.Feedback)
                        .With("PostedByID", feedbackMemberId)
                        .FederationOn("MemberQuestionAnswers", "MemberID", model.MemberID)
                        .AsNothing();
                    poda.Commit();
                }
                ShowMessage("Thanks for your feedback.");
                return RedirectToAction("Details", "Question", new { questionId = model.QuestionID });
            }
            else
            {
                return Create(model.QuestionID);
            }
        }
    }
}

Nanook/Nanook/Controllers/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Nanook.Entities;
using Nanook.Models;
using Nanook.Shared;

namespace Nanook.Controllers
{
    public class QuestionController : NanookController
    {
        [Authorize]
        [HttpGet]
        public ActionResult MyOutstandingQuestions()
        {
            var model = new QuestionMyOutstandingQuestionsViewModel();
            var memberId = Member.Data.ID;
            using (var poda = Poda.Factory.Create())
            {
                model.Questions = poda.Execute()
                    .ForPlainSQL("SELECT MemberQuestions.ID, Title, Question, MemberQuestions.PostedOn, COUNT(MemberQuestionAnswers.ID) AS AnswerCount " +
                                 "FROM MemberQuestions " +
                                 "LEFT JOIN MemberQuestionAnswers ON MemberQuestions.ID = MemberQuestionAnswers.QuestionID " +
                                 "WHERE MemberQuestions.MemberID = @MemberID AND MemberQuestions.AnswerID IS NULL " +
                                 "GROUP BY MemberQuestions.ID, Title, Question, MemberQuestions.PostedOn " +
                                 "ORDER BY MemberQuestions.PostedOn DESC ")
                    .With("MemberID", memberId)
                    .FederationOn("MemberQuestions", "MemberID", memberId)
                    .AsEntities<QuestionMyOutstandingQuestionsViewModel.QuestionItem>(reader => new QuestionMyOutstandingQuestionsViewModel.QuestionItem()
                    {
                        ID = (Guid)reader["ID"],
                        Title = (string)reader["Title"],
                        Question = (string)reader["Question"],
                        PostedOn = (DateTime)reader["PostedOn"],
                        AnswerCount = (int)reader["AnswerCount"]
                    });
            }
            return View(model);
        }

        [Authorize]
        [HttpGet]
        public ActionResult MyQuestions()
        {
            var model = new QuestionMyQuestionsViewModel();
            var memberId = Member.Data.ID;
            using (var poda = Poda.Factory.Create())
            {
                model.Questions = poda.Execute()
                    .ForPlainSQL("SELECT MemberQuestions.ID, Title, Question, MemberQuestions.PostedOn, COUNT(MemberQuestionAnswers.ID) AS AnswerCount, MemberQuestions.AnswerID " +
                                 "FROM MemberQuestions " +
                                 "LEFT JOIN MemberQuestionAnswers ON MemberQuestions.ID = MemberQuestionAnswers.QuestionID " +
                                 "WHERE MemberQuestions.MemberID = @MemberID " +
                                 "GROUP BY MemberQuestions.ID, Title, Question, MemberQuestions.PostedOn, MemberQuestions.AnswerID " +
                                 "ORDER BY MemberQuestions.PostedOn DESC ")
                    .With("MemberID", memberId)
                    .FederationOn("MemberQuestions", "MemberID", memberId)
                    .AsEntities<QuestionMyQuestionsViewModel.QuestionItem>(reader => new QuestionMyQuestionsViewModel.QuestionItem()
                    {
                        ID = (Guid)reader["ID"],
                        Title = (string)reader["Title"],
                        Question = (string)reader["Question"],
                        PostedOn = (DateTime)reader["PostedOn"],
                        AnswerCount = (int)reader["AnswerCount"],
                        HasValidAnswer = (reader["AnswerID"] != DBNull.Value)
                    });
            }
            return View(model);
        }

        [Authorize]
        [HttpGet]
        public ActionResult Edit(Guid questionId)
        {
            var memberId = Member.Data.ID;
            QuestionEditViewModel model = null;

            using (var poda = Poda.Factory.Create())
            {
                // load the question
                model = poda.Execute()
                    .ForPlainSQL("SELECT * FROM MemberQuestions WHERE ID = @ID")
                    .With("ID", questionId)
                    .FederationOn("MemberQuestions", "MemberID", memberId)
                    .AsEntities<QuestionEditViewModel>((reader) => new QuestionEditViewModel()
                    {
                        ID = questionId,
                        Question = (string)reader["Question"],
                        Title = (string)reader["Title"]
                    })
                    .FirstOrDefault();
                // load the tags
                var tags = poda.Execute()
                    .ForPlainSQL("SELECT Tag FROM MemberQuestionTags " +
                                 "LEFT JOIN Tags ON Tags.ID = MemberQuestionTags.TagID " +
                                 "WHERE QuestionID = @QuestionID " +
                                 "ORDER BY ReferenceCount DESC ")
                    .With("QuestionID", questionId)
                    .FederationOn("MemberQuestionTags", "MemberID", memberId)
                    .AsEntities<string>((reader) => (string)reader["Tag"]);
                model.Tags = tags.Combine(',');
            }
            return View(model);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Edit(QuestionEditViewModel model)
        {
            var memberId = Member.Data.ID;
            if (ModelState.IsValid)
            {
                using (var poda = Poda.Factory.Create())
                {
                    poda.Execute()
                        .ForPlainSQL("UPDATE MemberQuestions SET Title = @Title, Question = @Question " +
                                     "WHERE ID = @ID ")
                        .With("Title", model.Title)
                        .With("Question", model.Question)
                        .With("ID", model.ID)
                        .FederationOn("MemberQuestions", "MemberID", memberId)
                        .AsNothing();
                    poda.Commit();
                }
                ShowMessage("Your question had been changed successful.");
                return RedirectToAction("MyOutstandingQuestions");
            }
            else
            {
                return Edit(model.ID);
            }
        }

        [Authorize]
        [HttpGet]
        public ActionResult Create()
        {
            return View(new QuestionCreateViewModel());
        }

        [Authorize]
        [HttpPost]
        public ActionResult Create(QuestionCreateViewModel model)
        {
            var memberId = Member.Data.ID;
            var questionId = Guid.NewGuid();
            var tagsSpecified = model.Tags.Split(',')
                .Where(t => !string.IsNullOrWhiteSpace(t))
                .Select(t => t.ToLower())
                .ToList();
            using (var poda = Poda.Factory.Create())
            {
                // retrieve the existing tag list
                var tagsExisting = poda.Execute()
                    .ForPlainSQL("SELECT * FROM Tags")
                    .ReferenceOn("Tags")
                    .AsEntities<Tag>((reader) => new Tag()
                    {
                        ID = (Guid)reader["ID"],
                        Value = ((string)reader["Tag"]).ToLower(),
                        ReferneceCount = (long)reader["ReferenceCount"]
                    });
                // save new question
                poda.Execute()
                    .ForPlainSQL("INSERT INTO MemberQuestions (ID, MemberID, Title, Question) VALUES (@ID, @MemberID, @Title, @Question)")
                    .With("ID", questionId)
                    .With("MemberID", memberId)
                    .With("Title", model.Title)
                    .With("Question", model.Question)
                    .FederationOn("MemberQuestions", "MemberID", memberId)
                    .AsNothing();
                // save the tags and relationship
                Guid tagId;
                foreach (var tagSpecified in tagsSpecified)
                {
                    var tag = tagsExisting.Where(t => t.Value == tagSpecified).FirstOrDefault();
                    if (tag == null)
                    {
                        // save the new tag if it's no exist in tag database table
                        tagId = Guid.NewGuid();
                        poda.Execute()
                            .ForPlainSQL("INSERT INTO Tags (ID, Tag) VALUES (@ID, @Tag)")
                            .With("ID", tagId)
                            .With("Tag", tagSpecified)
                            .FederationOnAll()
                            .AsNothing();
                    }
                    else
                    {
                        tagId = tag.ID;
                        // update the reference count of the existing tag
                        poda.Execute()
                            .ForPlainSQL("UPDATE Tags SET ReferenceCount = @ReferenceCount WHERE ID = @ID")
                            .With("ReferenceCount", tag.ReferneceCount + 1)
                            .With("ID", tagId)
                            .FederationOnAll()
                            .AsNothing();
                    }
                    // create the question tag relationship
                    var questionTagId = Guid.NewGuid();
                    poda.Execute()
                        .ForPlainSQL("INSERT INTO MemberQuestionTags (ID, MemberID, QuestionID, TagID) VALUES (@ID, @MemberID, @QuestionID, @TagID)")
                        .With("ID", questionTagId)
                        .With("MemberID", memberId)
                        .With("QuestionID", questionId)
                        .With("TagID", tagId)
                        .FederationOn("MemberQuestionTags", "MemberID", memberId)
                        .AsNothing();
                    // save changes
                    poda.Commit();
                }
                // back to my outstanding question list

Nanook/Nanook/Views/Question/Create.cshtml
@model Nanook.Models.QuestionCreateViewModel

@{
    ViewBag.Title = "Ask a Question";
}

<h2>Ask a Question</h2>
<p>
    Use the form below to ask a new question. 
</p>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) { 
    <div>
        <fieldset>
            <div class="editor-label">
                @Html.LabelFor(m => m.Title)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(m => m.Title)
                @Html.ValidationMessageFor(m => m.Title)
            </div>

            <div class="editor-label">
                @Html.LabelFor(m => m.Question)
            </div>
            <div class="editor-field">
                @Html.TextAreaFor(m => m.Question)
                @Html.ValidationMessageFor(m => m.Question)
            </div>

            <div class="editor-label">
                @Html.LabelFor(m => m.Tags) 
                <i>
                    Please use comma ',' to separate the tags.
                </i>
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(m => m.Tags)
                @Html.ValidationMessageFor(m => m.Tags)
            </div>

            <p>
                <input type="submit" value="Ask" />
            </p>
        </fieldset>
    </div>
}

Nanook/Nanook/Views/Question/Details.cshtml
@model Nanook.Models.QuestionDetailsViewModel

@using Nanook.Shared;
@{
    ViewBag.Title = string.Format("Question: {0}", Model.Question.Title);
}

<div id="question">

    <table width="100%">
        <thead>
            <tr>
                <th style="width: 10%;">
                    @if (Model.Question.AnswerID.HasValue)
                    { 
                    <img src="/Content/answered.png" alt="Answered" />
                    }
                    else
                    { 
                    <img src="/Content/outstanding.png" alt="Answered" />
                    }
                </th>
                <th style="font-size: x-large;">
                    @Model.Question.Title
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td></td>
                <td style="font-size: larger;">
                    @Html.TextBlock(Model.Question.Content)
                </td>
            </tr>
            <tr>
                <td></td>
                <td style="text-align: right; font-style: italic;">
                    @Model.Question.PostedBy posted at @Model.Question.PostedOn.ToString()
                </td>
            </tr>
            <tr>
                <td></td>
                <td style="text-align: right;">
                    @if (Model.Question.IsMyQuestion)
                    {
                        if (Model.Question.AnswerID.HasValue)
                        { 
                            <!-- 
                            this action should navigate to another page and use POST or use Ajax and PUT 
                            HTTP method to update the question information rather than GET 
                            but since this is just a demo i utilize a normal GET linkage to implement
                            -->
                            @Html.ActionLink("Unmark Answer", "UnmarkAnswer", new { questionId = Model.Question.ID, postedById = Model.Question.PostedByID })
                        }
                        else
                        { 
                            @Html.ActionLink("Edit", "Edit", new { questionId = Model.Question.ID })
                        }
                    }
                    |
                    @Html.ActionLink("Add Feedback", "Create", "Feedback", new { questionId = Model.Question.ID }, null)
                </td>
            </tr>

            @if (Model.Question.AnswerID.HasValue)
            {
                var answer = Model.Feedbacks.Where(f => f.IsAnswer).FirstOrDefault();
                if (answer != null)
                { 
            <tr>
                <td>
                    <img src="/Content/answered.png" alt="Answered" />
                </td>
                <td style="font-size: larger;">
                    @Html.TextBlock(answer.Feedback)
                </td>
            </tr>
            <tr>
                <td></td>
                <td style="text-align: right; font-style: italic;">
                    @answer.PostedBy posted at @answer.PostedOn.ToString()
                </td>
            </tr>
                }
            }
            
            @foreach (var feedback in Model.Feedbacks.Where(f => !f.IsAnswer).OrderBy(f => f.PostedOn))
            { 
            <tr>
                <td></td>
                <td style="font-size: larger;">
                    @Html.TextBlock(feedback.Feedback)
                </td>
            </tr>
            <tr>
                <td></td>
                <td style="text-align: right; font-style: italic;">
                    @feedback.PostedBy posted at @feedback.PostedOn.ToString()
                </td>
            </tr>
            <tr>
                <td></td>
                <td style="text-align: right;">
                    @if (feedback.IsMyFeedback && !feedback.IsAnswer)
                    { 
                        @Html.ActionLink("Edit", "Edit", "Feedback", new { feedbackId = feedback.ID }, null)
                    }
                    |
                    <!-- 
                        this action should navigate to another page and use POST or use Ajax and PUT 
                        HTTP method to update the question information rather than GET 
                        but since this is just a demo i utilize a normal GET linkage to implement
                    -->
                    @if (Model.Question.IsMyQuestion && !feedback.IsAnswer)
                    { 
                        @Html.ActionLink("Mark Answer", "MarkAnswer", new { feedbackId = feedback.ID, questionId = Model.Question.ID, postedById = Model.Question.PostedByID })
                    }
                </td>
            </tr>
            }
            
            <tr>
                <td></td>
                <td style="text-align: right;">
                    @Html.ActionLink("Add Feedback", "Create", "Feedback", new { questionId = Model.Question.ID }, null)
                </td>
            </tr>
        </tbody>
    </table>
</div>

Nanook/Nanook/Views/Question/Edit.cshtml
@model Nanook.Models.QuestionEditViewModel

@{
    ViewBag.Title = "Edit Question";
}

<h2>Ask Question</h2>
<p>
    Use the form below to edit your question. 
</p>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) { 
    <div>
        <fieldset>
            <div class="editor-label">
                @Html.LabelFor(m => m.Title)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(m => m.Title)
                @Html.ValidationMessageFor(m => m.Title)
            </div>

            <div class="editor-label">
                @Html.LabelFor(m => m.Question)
            </div>
            <div class="editor-field">
                @Html.TextAreaFor(m => m.Question)
                @Html.ValidationMessageFor(m => m.Question)
            </div>

            <div class="editor-label">
                @Html.LabelFor(m => m.Tags) 
                <i>
                    Please use comma ',' to separate the tags.
                </i>
            </div>
            <div class="editor-field">
                <i>
                    Currently it's not allowed to update the tags.
                </i>
                @Html.TextBoxFor(m => m.Tags, new { disabled = "disabled" })
            </div>

            @Html.HiddenFor(m => m.ID)

            <p>
                <input type="submit" value="Submit" />
            </p>
        </fieldset>
    </div>
}

Nanook/Nanook/Views/Question/MyOutstandingQuestions.cshtml
@model Nanook.Models.QuestionMyOutstandingQuestionsViewModel

@using Nanook.Shared;

@{
    ViewBag.Title = "My Outstanding Questions";
}

<h2>My Outstanding Questions</h2>

<table>
    <thead>
        <tr>
            <th>Question</th>
            <th>Content</th>
            <th>Feedback(s)</th>
            <th>Posted On</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var question in Model.Questions) { 
        <tr>
            <td>
                @Html.ActionLink(question.Title, "Details", new { questionId = question.ID })
            </td>
            <td>
                @Html.TextBlock(question.Question)
            </td>
            <td>
                @question.AnswerCount.ToString()
            </td>
            <td>
                @question.PostedOn.ToString()
            </td>
        </tr>
        }
    </tbody>
</table>

Nanook/Nanook/Views/Question/MyQuestions.cshtml
@model Nanook.Models.QuestionMyQuestionsViewModel

@using Nanook.Shared;
@{
    ViewBag.Title = "My Questions";
}

<h2>My Questions</h2>

<table>
    <thead>
        <tr>
            <th></th>
            <th>Question</th>
            <th>Content</th>
            <th>Posted On</th>
            <th>Feedback(s)</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var question in Model.Questions) { 
        <tr>
            <td>
                @if (question.HasValidAnswer) {
                    <img src="/Content/answered.png" alt="Answered" />
                }
                else { 
                    <img src="/Content/outstanding.png" alt="Answered" />
                }
            </td>
            <td>
                @Html.ActionLink(question.Title, "Details", new { questionId = question.ID })
            </td>
            <td>
                @Html.TextBlock(question.Question)
            </td>
            <td>
                @question.PostedOn.ToString()
            </td>
            <td>
                @question.AnswerCount.ToString()
            </td>
        </tr>
        }
    </tbody>
</table>